# .streamlit/config.toml

[theme]

# Używamy ciemnej bazy
base = "dark"

# Żywy, zielony kolor jako główny akcent (dla przycisków, linków, etc.)
# Ten kolor jest inspirowany zielenią z Twojego przykładu
primaryColor = "#75f86f"

# Bardzo ciemne, niemal czarne tło
backgroundColor = "#000000"

# Tło dla kontenerów, np. pola do wgrywania plików (trochę jaśniejsze od tła)
secondaryBackgroundColor = "#FFFFFF"

# Jasny, biały tekst dla maksymalnego kontrastu
textColor = "#000000"

# Standardowa, czytelna czcionka
font = "sans serif"
