# .streamlit/config.toml

[theme]

# Używamy ciemnej bazy
base = "dark"

# Żywy, zielony kolor jako główny akcent (dla przycisków, linków, etc.)
# Ten kolor jest inspirowany zielenią z Twojego przykładu
primaryColor = "#5CFF87"

# Bardzo ciemne, niemal czarne tło
backgroundColor = "#0E1117"

# Tło dla kontenerów, np. pola do wgrywania plików (trochę jaśniejsze od tła)
secondaryBackgroundColor = "#1C1E26"

# Jasny, biały tekst dla maksymalnego kontrastu
textColor = "#FFFFFF"

# Standardowa, czytelna czcionka
font = "sans serif"
